# -*- coding: utf-8 -*-
"""PRODIGY_DS_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m9dvER_NujkfGYWeClXbWVwAoWjMrHUz
"""

# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('/content/ilpd+indian+liver+patient+dataset (1).zip')

df.columns = ['Age', 'Gender', 'Total_Bilirubin', 'Direct_Bilirubin', 'Alkphos_Alkaline_Phosphotase',
              'Sgpt_Alamine_Aminotransferase', 'Sgot_Aspartate_Aminotransferase', 'Total_Proteins',
              'Albumin', 'Albumin_and_Globulin_Ratio', 'Dataset_Label']

plt.figure(figsize=(10, 6))
plt.hist(df['Age'], bins=10, color='skyblue', edgecolor='black')
plt.title('Age Distribution of Patients')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

